### ISSUE TITLE
Cache collection metadata

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/specimenbrowser#14]
The home page currently requests every collection's metadata every time it is rendered. It should have some form of caching to avoid this occurring:

https://github.com/AtlasOfLivingAustralia/specimenbrowser/blob/c30747d5ed6cdff96526fea7a22310a6a70fa967/grails-app/controllers/au/org/ala/specimenbrowser/ViewController.groovy#L17

**Comment by nickdos** [comment]
@charvolant - this issue is sitting in QA, so has it been fixed in code somewhere? There are no commits recorded against it.

**Comment by nickdos** [comment]
@charvolant to track down something...
