### ISSUE TITLE
Specimen data - Coordinates

### ISSUE THREAD

**Issue by AlexisTindall** [AtlasOfLivingAustralia/specimenbrowser#5]
When a user clicks on the i button, to bring up specimen data, the field labelled coordinates only displays the latitude, please make it show latitude and longitude OR show them as two fields.

**Comment by djtfmartin** [comment]
This is fixed

http://specimens.ala.org.au/view/d29cc18a-6755-4eb6-905b-7711803ea4aa?recordId=f3d5f080-9b5c-46d7-b27f-7f1e5843a444
