### ISSUE TITLE
Alt-text - specimen details button

### ISSUE THREAD

**Issue by AlexisTindall** [AtlasOfLivingAustralia/specimenbrowser#6]
There is alt text for the zoom in, zoom out, full screen and image details buttons, but not for the specimen details button. Could you please add it for the specimen details button.

**Comment by djtfmartin** [comment]
Done

![screenshot 2015-05-20 14 48 53](https://cloud.githubusercontent.com/assets/444897/7727222/64ddcdba-feff-11e4-87a4-7c32c2b7b971.png)
