### ISSUE TITLE
Open occurrence records in new tab? 

### ISSUE THREAD

**Issue by AlexisTindall** [AtlasOfLivingAustralia/specimenbrowser#7]
To aid navigation, is it possible to open the occurrence record in a new tab when a user clicks on 'View full record details'? 

I ask this because I found that I got lost in navigation a couple of times. I opened a QM mollusc, clicked the i button to get more information, clicked the ‘View full details’ link, which took me to the occurrence record. When I clicked ‘return to search results’, it sent me to the full list of SA Museum records (unrelated to this current search, but possibly the last thing I searched for in the ALA). It means that a person browsing through the pictures might get lost and not easily return to the specimens browser.

**Comment by djtfmartin** [comment]
Im not sure about this one. 

Some users get annoyed with sites that create lots of tabs (I remember Donald in particular had a real dislike for this :) ). With the functionality as is users can opt to open the page in a new tab by right clicking and "Open in new tab".

**Comment by AlexisTindall** [comment]
No worries, just a suggestion. You've got more experience designing these things than I do, so happy to take your lead. 

I was trying to put myself in the shoes of a user who is browsing the collections using the Collections Browser, and who might not really want to go deep into the data. I feel like they need a path back to the Collections Browser once they've clicked out of it and into occurrence details. Perhaps we need to think about what they get when they click the 'return to search' button? But I understand that might be really complicated to make that same button do different things depending on the user's path. 

This might require some more thought, but is low priority compared to the other issues.

**Comment by djtfmartin** [comment]
marking as closed for now. we can always revisit / re-open
